// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240423134249_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("API.Models.Paciente", b =>
                {
                    b.Property<int?>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PacienteCpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteData")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteGenero")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteNotas")
                        .HasColumnType("TEXT");

                    b.Property<string>("PacienteTelefone")
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
