@API_HostAddress = http://localhost:5004

#P A C I E N T E
### CRIAR PACIENTES
POST http://localhost:5004/api/paciente/cadastrar
Content-Type: application/json

{
    "PacienteCpf": "10217875904",
    "PacienteNome": "2",
    "PacienteData": "3",
    "PacienteGenero": "4",
    "PacienteTelefone": "5",
    "PacienteNotas": "5"
}

### LISTAR PACIENTES
GET http://localhost:5004/api/paciente/listar
Accept: application/json

### BUSCAR PACIENTE POR CPF
GET {{API_HostAddress}}/api/paciente/buscarcpf/10217875904

### BUSCAR PACIENTE POR CPF
GET {{API_HostAddress}}/api/paciente/buscarnome/2

###
DELETE {{API_HostAddress}}/api/paciente/deletar/1

#C O N S U L T A

### CRIAR CONSULTAS
POST {{API_HostAddress}}/api/consulta/cadastrar
Content-Type: application/json

{
    "PacienteId": 2,
    "ConsultaData": "30/01/2003",
    "ConsultaNotas": "5"
}
### LISTAR CONSULTAS
GET {{API_HostAddress}}/api/consulta/listar