@API_HostAddress = http://localhost:5004

#P A C I E N T E!
### CRIAR PACIENTES
POST {{API_HostAddress}}/api/paciente/cadastrar
Content-Type: application/json

{
    "PacienteId": ,
    "ConsultaData": "",
    "ConsultaNotas": "5"
}

### LISTAR PACIENTES
GET {{API_HostAddress}}/api/paciente/listar
Accept: application/json

### BUSCAR PACIENTE POR CPF
GET {{API_HostAddress}}/api/paciente/buscarcpf/10217875904

### BUSCAR PACIENTE POR CPF
GET {{API_HostAddress}}/api/paciente/buscarnome/2

#C O N S U L T A!